services:
  - type: web
    name: prend-ton-temps-server
    runtime: node
    rootDir: .
    buildCommand: npm ci
    startCommand: npm run start --workspace=server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false

